// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dbmodels

import ()

type LinuxDistro struct {
	LinuxDistro string `db:"linux_distro" json:"linuxDistro"`
}

type LinuxUser struct {
	LinuxUserID   int64  `db:"linux_user_id" json:"linuxUserID"`
	LinuxUserName string `db:"linux_user_name" json:"linuxUserName"`
	LinuxDistro   string `db:"linux_distro" json:"linuxDistro"`
}

type SchemaMigration struct {
	Version string `db:"version" json:"version"`
}
