version: "3.8"
services:
  www:
    build:
      context: .
    image: csg33k/www:latest
    ports:
      - "3000:3000"
  db:
    image: postgres:15.1
    ports:
      - 5432:5432
    restart: always
    env_file: .env
