output = "dbmodels"
wipe = true
no-tests = true
pkgname = "dbmodels"


[psql]
dbname = "www"
host   = "localhost"
port   = 5432
user   = "postgres"
pass   = "secret"
schema = "public"
sslmode = "disable"