basePath: /
definitions:
  dbmodels.LinuxUser:
    properties:
      linuxDistro:
        type: string
      linuxUserID:
        type: integer
      linuxUserName:
        type: string
    type: object
info:
  contact: {}
  title: Golug Demo Code
  version: "1.0"
paths:
  /api/v1/distros/list:
    get:
      description: List all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
  /api/v1/users/:
    post:
      description: Create a New User
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dbmodels.LinuxUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dbmodels.LinuxUser'
  /api/v1/users/{id}:
    delete:
      description: Retrieves a User by ID
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dbmodels.LinuxUser'
    get:
      description: Retrieves a User by ID
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dbmodels.LinuxUser'
    put:
      description: Create a New User
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dbmodels.LinuxUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dbmodels.LinuxUser'
  /api/v1/users/list:
    get:
      description: List all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dbmodels.LinuxUser'
swagger: "2.0"
